// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJK71I4VQaH8qCmOnqraqfIXXBBzfl7k',
    appId: '1:257005347388:web:04a9fff547d29f3704d939',
    messagingSenderId: '257005347388',
    projectId: 'university-market-2b9d7',
    authDomain: 'university-market-2b9d7.firebaseapp.com',
    storageBucket: 'university-market-2b9d7.firebasestorage.app',
    measurementId: 'G-TR0QZLPPYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfHFnh_HrlDMb_6OcSpLScW8GhyDAd4Q',
    appId: '1:257005347388:android:eca6f7dc57468e1a04d939',
    messagingSenderId: '257005347388',
    projectId: 'university-market-2b9d7',
    storageBucket: 'university-market-2b9d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmoSNBkSz64MccrW238ChdUpdTf6yfmY4',
    appId: '1:257005347388:ios:54f102b1909f0c7304d939',
    messagingSenderId: '257005347388',
    projectId: 'university-market-2b9d7',
    storageBucket: 'university-market-2b9d7.firebasestorage.app',
    iosBundleId: 'com.example.universityMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmoSNBkSz64MccrW238ChdUpdTf6yfmY4',
    appId: '1:257005347388:ios:54f102b1909f0c7304d939',
    messagingSenderId: '257005347388',
    projectId: 'university-market-2b9d7',
    storageBucket: 'university-market-2b9d7.firebasestorage.app',
    iosBundleId: 'com.example.universityMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAJK71I4VQaH8qCmOnqraqfIXXBBzfl7k',
    appId: '1:257005347388:web:322f7c0cab8d41cf04d939',
    messagingSenderId: '257005347388',
    projectId: 'university-market-2b9d7',
    authDomain: 'university-market-2b9d7.firebaseapp.com',
    storageBucket: 'university-market-2b9d7.firebasestorage.app',
    measurementId: 'G-4PDW4YMJSC',
  );
}
